from .utils.nodes import NODE_CLASS_MAPPINGS as MAIN_NODE_CLASS_MAPPINGS
from .utils.nodes import NODE_DISPLAY_NAME_MAPPINGS as MAIN_NODE_DISPLAY_NAME_MAPPINGS
from .utils.helper_nodes import HELPER_NODE_CLASS_MAPPINGS
from .utils.helper_nodes import HELPER_NODE_DISPLAY_NAME_MAPPINGS

# Import VHS-SK nodes
try:
    from .VHS_SK import NODE_CLASS_MAPPINGS as VHS_NODE_CLASS_MAPPINGS
    from .VHS_SK import NODE_DISPLAY_NAME_MAPPINGS as VHS_NODE_DISPLAY_NAME_MAPPINGS
except ImportError as e:
    print(f"Warning: VHS-SK nodes not available: {e}")
    VHS_NODE_CLASS_MAPPINGS = {}
    VHS_NODE_DISPLAY_NAME_MAPPINGS = {}

# Combine main nodes, helper nodes, and VHS-SK nodes
NODE_CLASS_MAPPINGS = {**MAIN_NODE_CLASS_MAPPINGS, **HELPER_NODE_CLASS_MAPPINGS, **VHS_NODE_CLASS_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**MAIN_NODE_DISPLAY_NAME_MAPPINGS, **HELPER_NODE_DISPLAY_NAME_MAPPINGS, **VHS_NODE_DISPLAY_NAME_MAPPINGS}

WEB_DIRECTORY = "./web"

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]