"""
Media Describe Overrides Node

Provides paragraph-level override controls for the MediaDescribe node.
Allows users to replace specific paragraphs generated by Gemini with custom text.
"""

class MediaDescribeOverrides:
    """
    A ComfyUI custom node for configuring paragraph overrides for MediaDescribe.
    Outputs an OVERRIDES dictionary that can be connected to MediaDescribe node.
    """

    def __init__(self):
        pass

    @classmethod
    def INPUT_TYPES(s):
        """
        Return a dictionary which contains config for all input fields.
        All fields are optional - leave empty to use Gemini's output.
        """
        return {
            "required": {},
            "optional": {
                "prompt_prefix": ("STRING", {
                    "multiline": True,
                    "default": "",
                    "tooltip": "Text to prepend before the generated description (optional)"
                }),
                "override_subject": ("STRING", {
                    "multiline": True,
                    "default": "",
                    "tooltip": "Override text for SUBJECT paragraph (if provided, uses this instead of Gemini's output for subject)"
                }),
                "override_visual_style": ("STRING", {
                    "multiline": True,
                    "default": "",
                    "tooltip": "Override text for VISUAL STYLE paragraph (combines cinematic/aesthetic and stylization/tone - if provided, uses this instead of Gemini's output)"
                }),
                "override_clothing": ("STRING", {
                    "multiline": True,
                    "default": "",
                    "tooltip": "Override text for CLOTHING paragraph (if provided, uses this instead of Gemini's output for clothing)"
                }),
                "override_scene": ("STRING", {
                    "multiline": True,
                    "default": "",
                    "tooltip": "Override text for SCENE paragraph (video only - if provided, uses this instead of Gemini's output)"
                }),
                "override_action": ("STRING", {
                    "multiline": True,
                    "default": "",
                    "tooltip": "Override text for ACTION paragraph (video only - if provided, uses this instead of Gemini's output)"
                }),
            }
        }

    RETURN_TYPES = ("OVERRIDES",)
    RETURN_NAMES = ("overrides",)
    FUNCTION = "create_overrides"
    CATEGORY = "Swiss Army Knife 🔪/Media Caption"
    DESCRIPTION = (
        "Let users override individual MediaDescribe paragraphs (subject, visual style, clothing, scene, action) and prepend "
        "custom text before the generated description."
    )

    def create_overrides(self, prompt_prefix="", override_subject="", override_visual_style="",
                        override_clothing="", override_scene="", override_action=""):
        """
        Create an overrides dictionary from the input fields.

        Args:
            prompt_prefix: Text to prepend before the generated description
            override_subject: Override text for SUBJECT paragraph
            override_visual_style: Override text for VISUAL STYLE paragraph (combines cinematic/aesthetic and stylization/tone)
            override_clothing: Override text for CLOTHING paragraph
            override_scene: Override text for SCENE paragraph (video only)
            override_action: Override text for ACTION paragraph (video only)

        Returns:
            Dictionary containing all override values
        """
        overrides = {
            "prompt_prefix": prompt_prefix,
            "override_subject": override_subject,
            "override_visual_style": override_visual_style,
            "override_clothing": override_clothing,
            "override_scene": override_scene,
            "override_action": override_action,
            # Backwards compatibility with previous key name
            "override_movement": override_action
        }

        return (overrides,)
# Node display name mapping
NODE_DISPLAY_NAME_MAPPINGS = {
    "MediaDescribeOverrides": "Media Describe - Overrides"
}
